from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BusStopsGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bus_stop_id=None, bus_stop_name=None, bus_stop_lat=None, bus_stop_lon=None):  # noqa: E501
        """BusStopsGet200ResponseInner - a model defined in OpenAPI

        :param bus_stop_id: The bus_stop_id of this BusStopsGet200ResponseInner.  # noqa: E501
        :type bus_stop_id: str
        :param bus_stop_name: The bus_stop_name of this BusStopsGet200ResponseInner.  # noqa: E501
        :type bus_stop_name: str
        :param bus_stop_lat: The bus_stop_lat of this BusStopsGet200ResponseInner.  # noqa: E501
        :type bus_stop_lat: float
        :param bus_stop_lon: The bus_stop_lon of this BusStopsGet200ResponseInner.  # noqa: E501
        :type bus_stop_lon: float
        """
        self.openapi_types = {
            'bus_stop_id': str,
            'bus_stop_name': str,
            'bus_stop_lat': float,
            'bus_stop_lon': float
        }

        self.attribute_map = {
            'bus_stop_id': 'busStopId',
            'bus_stop_name': 'busStopName',
            'bus_stop_lat': 'busStopLat',
            'bus_stop_lon': 'busStopLon'
        }

        self._bus_stop_id = bus_stop_id
        self._bus_stop_name = bus_stop_name
        self._bus_stop_lat = bus_stop_lat
        self._bus_stop_lon = bus_stop_lon

    @classmethod
    def from_dict(cls, dikt) -> 'BusStopsGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _bus_stops_get_200_response_inner of this BusStopsGet200ResponseInner.  # noqa: E501
        :rtype: BusStopsGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bus_stop_id(self) -> str:
        """Gets the bus_stop_id of this BusStopsGet200ResponseInner.


        :return: The bus_stop_id of this BusStopsGet200ResponseInner.
        :rtype: str
        """
        return self._bus_stop_id

    @bus_stop_id.setter
    def bus_stop_id(self, bus_stop_id: str):
        """Sets the bus_stop_id of this BusStopsGet200ResponseInner.


        :param bus_stop_id: The bus_stop_id of this BusStopsGet200ResponseInner.
        :type bus_stop_id: str
        """

        self._bus_stop_id = bus_stop_id

    @property
    def bus_stop_name(self) -> str:
        """Gets the bus_stop_name of this BusStopsGet200ResponseInner.


        :return: The bus_stop_name of this BusStopsGet200ResponseInner.
        :rtype: str
        """
        return self._bus_stop_name

    @bus_stop_name.setter
    def bus_stop_name(self, bus_stop_name: str):
        """Sets the bus_stop_name of this BusStopsGet200ResponseInner.


        :param bus_stop_name: The bus_stop_name of this BusStopsGet200ResponseInner.
        :type bus_stop_name: str
        """

        self._bus_stop_name = bus_stop_name

    @property
    def bus_stop_lat(self) -> float:
        """Gets the bus_stop_lat of this BusStopsGet200ResponseInner.


        :return: The bus_stop_lat of this BusStopsGet200ResponseInner.
        :rtype: float
        """
        return self._bus_stop_lat

    @bus_stop_lat.setter
    def bus_stop_lat(self, bus_stop_lat: float):
        """Sets the bus_stop_lat of this BusStopsGet200ResponseInner.


        :param bus_stop_lat: The bus_stop_lat of this BusStopsGet200ResponseInner.
        :type bus_stop_lat: float
        """

        self._bus_stop_lat = bus_stop_lat

    @property
    def bus_stop_lon(self) -> float:
        """Gets the bus_stop_lon of this BusStopsGet200ResponseInner.


        :return: The bus_stop_lon of this BusStopsGet200ResponseInner.
        :rtype: float
        """
        return self._bus_stop_lon

    @bus_stop_lon.setter
    def bus_stop_lon(self, bus_stop_lon: float):
        """Sets the bus_stop_lon of this BusStopsGet200ResponseInner.


        :param bus_stop_lon: The bus_stop_lon of this BusStopsGet200ResponseInner.
        :type bus_stop_lon: float
        """

        self._bus_stop_lon = bus_stop_lon
