from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BusRoutesGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, route_id=None, route_name=None):  # noqa: E501
        """BusRoutesGet200ResponseInner - a model defined in OpenAPI

        :param route_id: The route_id of this BusRoutesGet200ResponseInner.  # noqa: E501
        :type route_id: str
        :param route_name: The route_name of this BusRoutesGet200ResponseInner.  # noqa: E501
        :type route_name: str
        """
        self.openapi_types = {
            'route_id': str,
            'route_name': str
        }

        self.attribute_map = {
            'route_id': 'routeId',
            'route_name': 'routeName'
        }

        self._route_id = route_id
        self._route_name = route_name

    @classmethod
    def from_dict(cls, dikt) -> 'BusRoutesGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _bus_routes_get_200_response_inner of this BusRoutesGet200ResponseInner.  # noqa: E501
        :rtype: BusRoutesGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def route_id(self) -> str:
        """Gets the route_id of this BusRoutesGet200ResponseInner.


        :return: The route_id of this BusRoutesGet200ResponseInner.
        :rtype: str
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id: str):
        """Sets the route_id of this BusRoutesGet200ResponseInner.


        :param route_id: The route_id of this BusRoutesGet200ResponseInner.
        :type route_id: str
        """

        self._route_id = route_id

    @property
    def route_name(self) -> str:
        """Gets the route_name of this BusRoutesGet200ResponseInner.


        :return: The route_name of this BusRoutesGet200ResponseInner.
        :rtype: str
        """
        return self._route_name

    @route_name.setter
    def route_name(self, route_name: str):
        """Sets the route_name of this BusRoutesGet200ResponseInner.


        :param route_name: The route_name of this BusRoutesGet200ResponseInner.
        :type route_name: str
        """

        self._route_name = route_name
