from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CursesGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, curse_id=None, name=None, description=None):  # noqa: E501
        """CursesGet200ResponseInner - a model defined in OpenAPI

        :param curse_id: The curse_id of this CursesGet200ResponseInner.  # noqa: E501
        :type curse_id: str
        :param name: The name of this CursesGet200ResponseInner.  # noqa: E501
        :type name: str
        :param description: The description of this CursesGet200ResponseInner.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'curse_id': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'curse_id': 'curseId',
            'name': 'name',
            'description': 'description'
        }

        self._curse_id = curse_id
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'CursesGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _curses_get_200_response_inner of this CursesGet200ResponseInner.  # noqa: E501
        :rtype: CursesGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def curse_id(self) -> str:
        """Gets the curse_id of this CursesGet200ResponseInner.


        :return: The curse_id of this CursesGet200ResponseInner.
        :rtype: str
        """
        return self._curse_id

    @curse_id.setter
    def curse_id(self, curse_id: str):
        """Sets the curse_id of this CursesGet200ResponseInner.


        :param curse_id: The curse_id of this CursesGet200ResponseInner.
        :type curse_id: str
        """

        self._curse_id = curse_id

    @property
    def name(self) -> str:
        """Gets the name of this CursesGet200ResponseInner.


        :return: The name of this CursesGet200ResponseInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CursesGet200ResponseInner.


        :param name: The name of this CursesGet200ResponseInner.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this CursesGet200ResponseInner.


        :return: The description of this CursesGet200ResponseInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CursesGet200ResponseInner.


        :param description: The description of this CursesGet200ResponseInner.
        :type description: str
        """

        self._description = description
