from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class HiderInfoGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lon=None, bus_station_name=None, bus_station_lat=None, bus_station_lon=None, bus_station_altitude=None, bus_station_bezirk=None, bus_station_gemeinde=None, distance_to_nearest_train_station=None, distance_to_nearest_mountain=None, distance_to_nearest_minigolf=None, distance_to_nearest_museum=None):  # noqa: E501
        """HiderInfoGet200Response - a model defined in OpenAPI

        :param lat: The lat of this HiderInfoGet200Response.  # noqa: E501
        :type lat: float
        :param lon: The lon of this HiderInfoGet200Response.  # noqa: E501
        :type lon: float
        :param bus_station_name: The bus_station_name of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_name: str
        :param bus_station_lat: The bus_station_lat of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_lat: float
        :param bus_station_lon: The bus_station_lon of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_lon: float
        :param bus_station_altitude: The bus_station_altitude of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_altitude: float
        :param bus_station_bezirk: The bus_station_bezirk of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_bezirk: str
        :param bus_station_gemeinde: The bus_station_gemeinde of this HiderInfoGet200Response.  # noqa: E501
        :type bus_station_gemeinde: str
        :param distance_to_nearest_train_station: The distance_to_nearest_train_station of this HiderInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_train_station: float
        :param distance_to_nearest_mountain: The distance_to_nearest_mountain of this HiderInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_mountain: float
        :param distance_to_nearest_minigolf: The distance_to_nearest_minigolf of this HiderInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_minigolf: float
        :param distance_to_nearest_museum: The distance_to_nearest_museum of this HiderInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_museum: float
        """
        self.openapi_types = {
            'lat': float,
            'lon': float,
            'bus_station_name': str,
            'bus_station_lat': float,
            'bus_station_lon': float,
            'bus_station_altitude': float,
            'bus_station_bezirk': str,
            'bus_station_gemeinde': str,
            'distance_to_nearest_train_station': float,
            'distance_to_nearest_mountain': float,
            'distance_to_nearest_minigolf': float,
            'distance_to_nearest_museum': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon',
            'bus_station_name': 'busStationName',
            'bus_station_lat': 'busStationLat',
            'bus_station_lon': 'busStationLon',
            'bus_station_altitude': 'busStationAltitude',
            'bus_station_bezirk': 'busStationBezirk',
            'bus_station_gemeinde': 'busStationGemeinde',
            'distance_to_nearest_train_station': 'distanceToNearestTrainStation',
            'distance_to_nearest_mountain': 'distanceToNearestMountain',
            'distance_to_nearest_minigolf': 'distanceToNearestMinigolf',
            'distance_to_nearest_museum': 'distanceToNearestMuseum'
        }

        self._lat = lat
        self._lon = lon
        self._bus_station_name = bus_station_name
        self._bus_station_lat = bus_station_lat
        self._bus_station_lon = bus_station_lon
        self._bus_station_altitude = bus_station_altitude
        self._bus_station_bezirk = bus_station_bezirk
        self._bus_station_gemeinde = bus_station_gemeinde
        self._distance_to_nearest_train_station = distance_to_nearest_train_station
        self._distance_to_nearest_mountain = distance_to_nearest_mountain
        self._distance_to_nearest_minigolf = distance_to_nearest_minigolf
        self._distance_to_nearest_museum = distance_to_nearest_museum

    @classmethod
    def from_dict(cls, dikt) -> 'HiderInfoGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _hider_info_get_200_response of this HiderInfoGet200Response.  # noqa: E501
        :rtype: HiderInfoGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this HiderInfoGet200Response.


        :return: The lat of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this HiderInfoGet200Response.


        :param lat: The lat of this HiderInfoGet200Response.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this HiderInfoGet200Response.


        :return: The lon of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this HiderInfoGet200Response.


        :param lon: The lon of this HiderInfoGet200Response.
        :type lon: float
        """

        self._lon = lon

    @property
    def bus_station_name(self) -> str:
        """Gets the bus_station_name of this HiderInfoGet200Response.


        :return: The bus_station_name of this HiderInfoGet200Response.
        :rtype: str
        """
        return self._bus_station_name

    @bus_station_name.setter
    def bus_station_name(self, bus_station_name: str):
        """Sets the bus_station_name of this HiderInfoGet200Response.


        :param bus_station_name: The bus_station_name of this HiderInfoGet200Response.
        :type bus_station_name: str
        """

        self._bus_station_name = bus_station_name

    @property
    def bus_station_lat(self) -> float:
        """Gets the bus_station_lat of this HiderInfoGet200Response.


        :return: The bus_station_lat of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._bus_station_lat

    @bus_station_lat.setter
    def bus_station_lat(self, bus_station_lat: float):
        """Sets the bus_station_lat of this HiderInfoGet200Response.


        :param bus_station_lat: The bus_station_lat of this HiderInfoGet200Response.
        :type bus_station_lat: float
        """

        self._bus_station_lat = bus_station_lat

    @property
    def bus_station_lon(self) -> float:
        """Gets the bus_station_lon of this HiderInfoGet200Response.


        :return: The bus_station_lon of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._bus_station_lon

    @bus_station_lon.setter
    def bus_station_lon(self, bus_station_lon: float):
        """Sets the bus_station_lon of this HiderInfoGet200Response.


        :param bus_station_lon: The bus_station_lon of this HiderInfoGet200Response.
        :type bus_station_lon: float
        """

        self._bus_station_lon = bus_station_lon

    @property
    def bus_station_altitude(self) -> float:
        """Gets the bus_station_altitude of this HiderInfoGet200Response.


        :return: The bus_station_altitude of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._bus_station_altitude

    @bus_station_altitude.setter
    def bus_station_altitude(self, bus_station_altitude: float):
        """Sets the bus_station_altitude of this HiderInfoGet200Response.


        :param bus_station_altitude: The bus_station_altitude of this HiderInfoGet200Response.
        :type bus_station_altitude: float
        """

        self._bus_station_altitude = bus_station_altitude

    @property
    def bus_station_bezirk(self) -> str:
        """Gets the bus_station_bezirk of this HiderInfoGet200Response.


        :return: The bus_station_bezirk of this HiderInfoGet200Response.
        :rtype: str
        """
        return self._bus_station_bezirk

    @bus_station_bezirk.setter
    def bus_station_bezirk(self, bus_station_bezirk: str):
        """Sets the bus_station_bezirk of this HiderInfoGet200Response.


        :param bus_station_bezirk: The bus_station_bezirk of this HiderInfoGet200Response.
        :type bus_station_bezirk: str
        """

        self._bus_station_bezirk = bus_station_bezirk

    @property
    def bus_station_gemeinde(self) -> str:
        """Gets the bus_station_gemeinde of this HiderInfoGet200Response.


        :return: The bus_station_gemeinde of this HiderInfoGet200Response.
        :rtype: str
        """
        return self._bus_station_gemeinde

    @bus_station_gemeinde.setter
    def bus_station_gemeinde(self, bus_station_gemeinde: str):
        """Sets the bus_station_gemeinde of this HiderInfoGet200Response.


        :param bus_station_gemeinde: The bus_station_gemeinde of this HiderInfoGet200Response.
        :type bus_station_gemeinde: str
        """

        self._bus_station_gemeinde = bus_station_gemeinde

    @property
    def distance_to_nearest_train_station(self) -> float:
        """Gets the distance_to_nearest_train_station of this HiderInfoGet200Response.


        :return: The distance_to_nearest_train_station of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_train_station

    @distance_to_nearest_train_station.setter
    def distance_to_nearest_train_station(self, distance_to_nearest_train_station: float):
        """Sets the distance_to_nearest_train_station of this HiderInfoGet200Response.


        :param distance_to_nearest_train_station: The distance_to_nearest_train_station of this HiderInfoGet200Response.
        :type distance_to_nearest_train_station: float
        """

        self._distance_to_nearest_train_station = distance_to_nearest_train_station

    @property
    def distance_to_nearest_mountain(self) -> float:
        """Gets the distance_to_nearest_mountain of this HiderInfoGet200Response.


        :return: The distance_to_nearest_mountain of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_mountain

    @distance_to_nearest_mountain.setter
    def distance_to_nearest_mountain(self, distance_to_nearest_mountain: float):
        """Sets the distance_to_nearest_mountain of this HiderInfoGet200Response.


        :param distance_to_nearest_mountain: The distance_to_nearest_mountain of this HiderInfoGet200Response.
        :type distance_to_nearest_mountain: float
        """

        self._distance_to_nearest_mountain = distance_to_nearest_mountain

    @property
    def distance_to_nearest_minigolf(self) -> float:
        """Gets the distance_to_nearest_minigolf of this HiderInfoGet200Response.


        :return: The distance_to_nearest_minigolf of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_minigolf

    @distance_to_nearest_minigolf.setter
    def distance_to_nearest_minigolf(self, distance_to_nearest_minigolf: float):
        """Sets the distance_to_nearest_minigolf of this HiderInfoGet200Response.


        :param distance_to_nearest_minigolf: The distance_to_nearest_minigolf of this HiderInfoGet200Response.
        :type distance_to_nearest_minigolf: float
        """

        self._distance_to_nearest_minigolf = distance_to_nearest_minigolf

    @property
    def distance_to_nearest_museum(self) -> float:
        """Gets the distance_to_nearest_museum of this HiderInfoGet200Response.


        :return: The distance_to_nearest_museum of this HiderInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_museum

    @distance_to_nearest_museum.setter
    def distance_to_nearest_museum(self, distance_to_nearest_museum: float):
        """Sets the distance_to_nearest_museum of this HiderInfoGet200Response.


        :param distance_to_nearest_museum: The distance_to_nearest_museum of this HiderInfoGet200Response.
        :type distance_to_nearest_museum: float
        """

        self._distance_to_nearest_museum = distance_to_nearest_museum
