from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class QuestionsGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, already_asked=None):  # noqa: E501
        """QuestionsGet200ResponseInner - a model defined in OpenAPI

        :param id: The id of this QuestionsGet200ResponseInner.  # noqa: E501
        :type id: str
        :param name: The name of this QuestionsGet200ResponseInner.  # noqa: E501
        :type name: str
        :param description: The description of this QuestionsGet200ResponseInner.  # noqa: E501
        :type description: str
        :param already_asked: The already_asked of this QuestionsGet200ResponseInner.  # noqa: E501
        :type already_asked: bool
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'description': str,
            'already_asked': bool
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'already_asked': 'alreadyAsked'
        }

        self._id = id
        self._name = name
        self._description = description
        self._already_asked = already_asked

    @classmethod
    def from_dict(cls, dikt) -> 'QuestionsGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _questions_get_200_response_inner of this QuestionsGet200ResponseInner.  # noqa: E501
        :rtype: QuestionsGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this QuestionsGet200ResponseInner.


        :return: The id of this QuestionsGet200ResponseInner.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this QuestionsGet200ResponseInner.


        :param id: The id of this QuestionsGet200ResponseInner.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this QuestionsGet200ResponseInner.


        :return: The name of this QuestionsGet200ResponseInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this QuestionsGet200ResponseInner.


        :param name: The name of this QuestionsGet200ResponseInner.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this QuestionsGet200ResponseInner.


        :return: The description of this QuestionsGet200ResponseInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this QuestionsGet200ResponseInner.


        :param description: The description of this QuestionsGet200ResponseInner.
        :type description: str
        """

        self._description = description

    @property
    def already_asked(self) -> bool:
        """Gets the already_asked of this QuestionsGet200ResponseInner.


        :return: The already_asked of this QuestionsGet200ResponseInner.
        :rtype: bool
        """
        return self._already_asked

    @already_asked.setter
    def already_asked(self, already_asked: bool):
        """Sets the already_asked of this QuestionsGet200ResponseInner.


        :param already_asked: The already_asked of this QuestionsGet200ResponseInner.
        :type already_asked: bool
        """

        self._already_asked = already_asked
