from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SeekerInfoGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lon=None, altitude=None, bezirk=None, gemeinde=None, distance_to_nearest_train_station=None, distance_to_nearest_mountain=None, distance_to_nearest_minigolf=None, distance_to_nearest_museum=None):  # noqa: E501
        """SeekerInfoGet200Response - a model defined in OpenAPI

        :param lat: The lat of this SeekerInfoGet200Response.  # noqa: E501
        :type lat: float
        :param lon: The lon of this SeekerInfoGet200Response.  # noqa: E501
        :type lon: float
        :param altitude: The altitude of this SeekerInfoGet200Response.  # noqa: E501
        :type altitude: float
        :param bezirk: The bezirk of this SeekerInfoGet200Response.  # noqa: E501
        :type bezirk: str
        :param gemeinde: The gemeinde of this SeekerInfoGet200Response.  # noqa: E501
        :type gemeinde: str
        :param distance_to_nearest_train_station: The distance_to_nearest_train_station of this SeekerInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_train_station: float
        :param distance_to_nearest_mountain: The distance_to_nearest_mountain of this SeekerInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_mountain: float
        :param distance_to_nearest_minigolf: The distance_to_nearest_minigolf of this SeekerInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_minigolf: float
        :param distance_to_nearest_museum: The distance_to_nearest_museum of this SeekerInfoGet200Response.  # noqa: E501
        :type distance_to_nearest_museum: float
        """
        self.openapi_types = {
            'lat': float,
            'lon': float,
            'altitude': float,
            'bezirk': str,
            'gemeinde': str,
            'distance_to_nearest_train_station': float,
            'distance_to_nearest_mountain': float,
            'distance_to_nearest_minigolf': float,
            'distance_to_nearest_museum': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon',
            'altitude': 'altitude',
            'bezirk': 'bezirk',
            'gemeinde': 'gemeinde',
            'distance_to_nearest_train_station': 'distanceToNearestTrainStation',
            'distance_to_nearest_mountain': 'distanceToNearestMountain',
            'distance_to_nearest_minigolf': 'distanceToNearestMinigolf',
            'distance_to_nearest_museum': 'distanceToNearestMuseum'
        }

        self._lat = lat
        self._lon = lon
        self._altitude = altitude
        self._bezirk = bezirk
        self._gemeinde = gemeinde
        self._distance_to_nearest_train_station = distance_to_nearest_train_station
        self._distance_to_nearest_mountain = distance_to_nearest_mountain
        self._distance_to_nearest_minigolf = distance_to_nearest_minigolf
        self._distance_to_nearest_museum = distance_to_nearest_museum

    @classmethod
    def from_dict(cls, dikt) -> 'SeekerInfoGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _seeker_info_get_200_response of this SeekerInfoGet200Response.  # noqa: E501
        :rtype: SeekerInfoGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this SeekerInfoGet200Response.


        :return: The lat of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this SeekerInfoGet200Response.


        :param lat: The lat of this SeekerInfoGet200Response.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this SeekerInfoGet200Response.


        :return: The lon of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this SeekerInfoGet200Response.


        :param lon: The lon of this SeekerInfoGet200Response.
        :type lon: float
        """

        self._lon = lon

    @property
    def altitude(self) -> float:
        """Gets the altitude of this SeekerInfoGet200Response.


        :return: The altitude of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude: float):
        """Sets the altitude of this SeekerInfoGet200Response.


        :param altitude: The altitude of this SeekerInfoGet200Response.
        :type altitude: float
        """

        self._altitude = altitude

    @property
    def bezirk(self) -> str:
        """Gets the bezirk of this SeekerInfoGet200Response.


        :return: The bezirk of this SeekerInfoGet200Response.
        :rtype: str
        """
        return self._bezirk

    @bezirk.setter
    def bezirk(self, bezirk: str):
        """Sets the bezirk of this SeekerInfoGet200Response.


        :param bezirk: The bezirk of this SeekerInfoGet200Response.
        :type bezirk: str
        """

        self._bezirk = bezirk

    @property
    def gemeinde(self) -> str:
        """Gets the gemeinde of this SeekerInfoGet200Response.


        :return: The gemeinde of this SeekerInfoGet200Response.
        :rtype: str
        """
        return self._gemeinde

    @gemeinde.setter
    def gemeinde(self, gemeinde: str):
        """Sets the gemeinde of this SeekerInfoGet200Response.


        :param gemeinde: The gemeinde of this SeekerInfoGet200Response.
        :type gemeinde: str
        """

        self._gemeinde = gemeinde

    @property
    def distance_to_nearest_train_station(self) -> float:
        """Gets the distance_to_nearest_train_station of this SeekerInfoGet200Response.


        :return: The distance_to_nearest_train_station of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_train_station

    @distance_to_nearest_train_station.setter
    def distance_to_nearest_train_station(self, distance_to_nearest_train_station: float):
        """Sets the distance_to_nearest_train_station of this SeekerInfoGet200Response.


        :param distance_to_nearest_train_station: The distance_to_nearest_train_station of this SeekerInfoGet200Response.
        :type distance_to_nearest_train_station: float
        """

        self._distance_to_nearest_train_station = distance_to_nearest_train_station

    @property
    def distance_to_nearest_mountain(self) -> float:
        """Gets the distance_to_nearest_mountain of this SeekerInfoGet200Response.


        :return: The distance_to_nearest_mountain of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_mountain

    @distance_to_nearest_mountain.setter
    def distance_to_nearest_mountain(self, distance_to_nearest_mountain: float):
        """Sets the distance_to_nearest_mountain of this SeekerInfoGet200Response.


        :param distance_to_nearest_mountain: The distance_to_nearest_mountain of this SeekerInfoGet200Response.
        :type distance_to_nearest_mountain: float
        """

        self._distance_to_nearest_mountain = distance_to_nearest_mountain

    @property
    def distance_to_nearest_minigolf(self) -> float:
        """Gets the distance_to_nearest_minigolf of this SeekerInfoGet200Response.


        :return: The distance_to_nearest_minigolf of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_minigolf

    @distance_to_nearest_minigolf.setter
    def distance_to_nearest_minigolf(self, distance_to_nearest_minigolf: float):
        """Sets the distance_to_nearest_minigolf of this SeekerInfoGet200Response.


        :param distance_to_nearest_minigolf: The distance_to_nearest_minigolf of this SeekerInfoGet200Response.
        :type distance_to_nearest_minigolf: float
        """

        self._distance_to_nearest_minigolf = distance_to_nearest_minigolf

    @property
    def distance_to_nearest_museum(self) -> float:
        """Gets the distance_to_nearest_museum of this SeekerInfoGet200Response.


        :return: The distance_to_nearest_museum of this SeekerInfoGet200Response.
        :rtype: float
        """
        return self._distance_to_nearest_museum

    @distance_to_nearest_museum.setter
    def distance_to_nearest_museum(self, distance_to_nearest_museum: float):
        """Sets the distance_to_nearest_museum of this SeekerInfoGet200Response.


        :param distance_to_nearest_museum: The distance_to_nearest_museum of this SeekerInfoGet200Response.
        :type distance_to_nearest_museum: float
        """

        self._distance_to_nearest_museum = distance_to_nearest_museum
