from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SeekerGetCoordinatesGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lon=None):  # noqa: E501
        """SeekerGetCoordinatesGet200Response - a model defined in OpenAPI

        :param lat: The lat of this SeekerGetCoordinatesGet200Response.  # noqa: E501
        :type lat: float
        :param lon: The lon of this SeekerGetCoordinatesGet200Response.  # noqa: E501
        :type lon: float
        """
        self.openapi_types = {
            'lat': float,
            'lon': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon'
        }

        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt) -> 'SeekerGetCoordinatesGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _seeker_get_coordinates_get_200_response of this SeekerGetCoordinatesGet200Response.  # noqa: E501
        :rtype: SeekerGetCoordinatesGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this SeekerGetCoordinatesGet200Response.


        :return: The lat of this SeekerGetCoordinatesGet200Response.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this SeekerGetCoordinatesGet200Response.


        :param lat: The lat of this SeekerGetCoordinatesGet200Response.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this SeekerGetCoordinatesGet200Response.


        :return: The lon of this SeekerGetCoordinatesGet200Response.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this SeekerGetCoordinatesGet200Response.


        :param lon: The lon of this SeekerGetCoordinatesGet200Response.
        :type lon: float
        """

        self._lon = lon
